-- W7-1 RLS 기본 활성화 (1차).
-- 모든 도메인 테이블에 RLS enable + 명시적 policy 없음 → anon 키 deny by default.
-- service_role(우리 Prisma DIRECT_URL)은 RLS bypass라 코드 영향 0.
--
-- 2차(W8+): authenticated user 기반 select policy 추가 + Realtime broadcast
-- channel access 검증으로 학부모 trip 직접 구독도 RLS로 막을 예정.
--
-- _prisma_migrations 등 시스템 테이블은 활성화 X.

ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vehicle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Staff" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffInvite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Stop" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Route" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RouteStop" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RouteStudent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Student" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Guardian" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuardianLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuardianInvite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuardianInviteStudent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Trip" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BoardingEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LocationPing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SafetyCheck" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AbsenceRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffPushSubscription" ENABLE ROW LEVEL SECURITY;
